"""empty message

Revision ID: 456309418f38
Revises: c50b0066022c
Create Date: 2023-04-24 10:39:50.548252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '456309418f38'
down_revision = 'c50b0066022c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_login', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_login', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
